#!/bin/bash
# Generated By: Claude Code (Claude Opus 4.6)
# Entrypoint for the Claude Code sandbox container.
#
# Symlinks ~/.claude.json into the persistent auth volume (/home/node/.claude)
# so onboarding state (theme selection, first-run flags) survives container
# restarts. Without this, Claude Code shows the setup wizard on every run.

set -euo pipefail

PERSISTENT_DIR="/home/node/.claude"
CONFIG_FILE="/home/node/.claude.json"
PERSISTENT_CONFIG="${PERSISTENT_DIR}/.claude.json"

# If the persistent volume has a saved config, symlink it into place.
# If not, create the symlink target so Claude Code writes there directly.
if [ -f "$PERSISTENT_CONFIG" ]; then
    ln -sf "$PERSISTENT_CONFIG" "$CONFIG_FILE"
elif [ -d "$PERSISTENT_DIR" ]; then
    # Create an empty JSON object in the persistent volume and symlink to it.
    # Claude Code will populate it on first run.
    echo '{}' > "$PERSISTENT_CONFIG"
    ln -sf "$PERSISTENT_CONFIG" "$CONFIG_FILE"
fi

exec "$@"
