#!/usr/bin/env bash
# Agentic build loop — runs tasks/RUN.md until APPROVED or BLOCKED
# Generated By: Claude Code (Claude Opus 4.6)
#
# Usage:
#   ./loop.sh                    # Use models from orchestrator.yaml
#   ./loop.sh --model sonnet     # Override all stages to one model

set -euo pipefail

# ── Parse arguments ───────────────────────────────────────────
MODEL_OVERRIDE=""
if [ "${1:-}" = "--model" ] && [ -n "${2:-}" ]; then
  MODEL_OVERRIDE="$2"
  echo "Model override: using $MODEL_OVERRIDE for all stages"
fi

# ── Read orchestrator.yaml ────────────────────────────────────
CONF="orchestrator.yaml"
read_yaml() {
  local key="$1"
  local default="$2"
  if [ -f "$CONF" ]; then
    local val
    val=$(grep "^  *${key}:" "$CONF" 2>/dev/null | sed 's/^[^:]*: *//' | sed 's/ *#.*//' | tr -d '"' | head -1)
    echo "${val:-$default}"
  else
    echo "$default"
  fi
}

DEV_MODEL=$(read_yaml "dev" "sonnet")
TEST_MODEL=$(read_yaml "test" "sonnet")
REVIEW_MODEL=$(read_yaml "review" "sonnet")
JUDGE_MODEL=$(read_yaml "judge" "opus")

# ── Resolve model for current stage ──────────────────────────
get_stage_model() {
  local next="$1"
  if [ -n "$MODEL_OVERRIDE" ]; then
    echo "$MODEL_OVERRIDE"
    return
  fi
  case "$next" in
    *DEV*)    echo "$DEV_MODEL" ;;
    *TEST*)   echo "$TEST_MODEL" ;;
    *REVIEW*) echo "$REVIEW_MODEL" ;;
    *JUDGE*)  echo "$JUDGE_MODEL" ;;
    *)        echo "sonnet" ;;
  esac
}

# ── Main loop ─────────────────────────────────────────────────
while true; do
  NEXT=$(grep "→ NEXT:" tasks/TASK_LIST.md | head -1)

  if [ -z "$NEXT" ]; then
    echo "No cursor found in tasks/TASK_LIST.md — nothing to do."
    break
  fi

  STAGE_MODEL=$(get_stage_model "$NEXT")

  echo ""
  echo "════════════════════════════════════════════════"
  echo "  $NEXT"
  echo "  Model: $STAGE_MODEL"
  echo "════════════════════════════════════════════════"
  echo ""

  SANDBOX_CMD=(tools/run-claude-sandbox.sh --task-file tasks/RUN.md --model "$STAGE_MODEL")

  "${SANDBOX_CMD[@]}" </dev/null || true

  STATUS=$(tr -d '[:space:]' < tasks/BUILD_STATUS.md)

  if [ "$STATUS" = "APPROVED" ]; then
    echo ""
    echo "Build approved by final judge."
    break
  fi

  if [[ "$STATUS" == FAILED* ]]; then
    echo ""
    echo "Final judge failed — see tasks/feedback/final-judge.md"
    break
  fi

  # Check for BLOCKED
  if grep -q '\[BLOCKED\]' tasks/TASK_LIST.md; then
    echo ""
    echo "Task blocked after max retries — human intervention required."
    echo "Check tasks/TASK_LIST.md for [BLOCKED] entries."
    break
  fi

  NEXT=$(grep "→ NEXT:" tasks/TASK_LIST.md | head -1)
  echo "Next: $NEXT"
done
