#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.6)
# Validate prerequisites for the agentic build loop.
# Exit 0 if ready, exit 1 if critical prereqs missing.
# Outputs structured status for the agentic-loop skill to consume.

set -euo pipefail

ERRORS=0

check() {
  local label="$1" path="$2" kind="$3"
  if [ "$kind" = "file" ] && [ -f "$path" ]; then
    echo "OK   $label"
  elif [ "$kind" = "dir" ] && [ -d "$path" ]; then
    echo "OK   $label"
  elif [ "$kind" = "exec" ] && [ -x "$path" ]; then
    echo "OK   $label"
  else
    echo "MISS $label ($path)"
    ERRORS=$((ERRORS + 1))
  fi
}

echo "=== Prereq Check ==="
check "TASK_LIST.md"    "tasks/TASK_LIST.md"    file
check "BUILD_STATUS.md" "tasks/BUILD_STATUS.md" file
check "loop.sh"         "loop.sh"               exec
check "personas/"       "tasks/personas"        dir
check "specs/"          "tasks/specs"           dir

if [ -f "orchestrator.yaml" ]; then
  echo "OK   orchestrator.yaml"
else
  echo "WARN orchestrator.yaml (missing, using defaults)"
fi

echo ""
echo "=== Task Specs ==="
ls -1 tasks/specs/ 2>/dev/null || echo "(none)"

echo ""
echo "=== Personas ==="
ls -1 tasks/personas/ 2>/dev/null || echo "(none)"

echo ""
echo "=== Current Cursor ==="
grep "→ NEXT:" tasks/TASK_LIST.md 2>/dev/null || echo "(no cursor found)"

echo ""
echo "=== Build Status ==="
cat tasks/BUILD_STATUS.md 2>/dev/null || echo "(not found)"

if [ "$ERRORS" -gt 0 ]; then
  echo ""
  echo "RESULT: $ERRORS critical prereqs missing. Run agentic-scaffold first."
  exit 1
fi

echo ""
echo "RESULT: Ready to run."
exit 0
